DWAPlannerROS:
  controller_frequency: 20.0
  max_trans_vel: 0.8
  min_trans_vel: 0.1
  max_vel_x: 0.5
  max_vel_y: 0.0
  min_vel_x: 0.0
  min_vel_y: 0.0
  max_rot_vel: 0.5
  min_rot_vel: 0.15
  acc_lim_th: 1.57
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  sim_time: 2.0
  forward_point_distance: 0.325
  occdist_scale: 5.0
  vx_samples: 10
  vy_samples: 1
  vtheta_samples: 50
  stop_time_buffer: 0.3
  path_distance_bias: 1.0
  goal_distance_bias: 20.0
  latch_xy_goal_tolerance: true
  max_scaling_factor: 0.1
  oscillation_reset_dist: 0.1
  publish_cost_grid_pc: true
  publish_traj_pc: true
  sim_granularity: 0.1
