#Parameters that are common to the local and global costmaps
footprint: [[-0.25, -0.225], [-0.325, 0], [-0.25, 0.225], [0.25, 0.225], [0.325, 0], [0.25, -0.225]]
obstacle_range: 2.5
#inflation_radius: 0.55
raytrace_range: 3.0
transform_tolerance: 5.0
map_type: costmap
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 0.5} 
robot_base_frame: base_link